### ISSUE TITLE
Remapping no longer works under macOS Ventura (or new Logi Options+)

### ISSUE THREAD

**Issue by iamkedzia** [simonescanzani/universal_mx_keys_remap#4]
Self explanatory, running macOS Ventura 13.0 and latest Logitech Options +. The keyboard's FW is 12.1.13.

**Comment by silverback97** [comment]
Hi, thank you for the feedback. I am currently using Logi Options + on Monterey but am not experiencing any kind of errors. Maybe as you said something might have changed on MacOS Ventura.
After the official release of the Stable of MacOS Ventura, if I encounter problems I will certainly proceed to make any fixes. I will not fail to update the guide.
I state that I will not try / install Ventura before the first major release (13.1) for reasons of reliability in the workplace.

But I can try to make a suggestion.
Try installing old legacy software from logitech: Logitech Control Center.
In the first versions I wrote I needed this version for the vendor ID to be detected correctly in order to make the keyboard remapping work.
Of course if this doesn't work, I ask you to wait a few weeks before I will upgrade my Mac.
